# Generated by Django 5.0.4 on 2024-05-03 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
    ]
