# Generated by Django 5.0.4 on 2024-05-03 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20240503_1847'),
    ]

    operations = [
    ]
