# Generated by Django 5.0.6 on 2024-05-20 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scootsapp', '0006_rename_pword_user_k'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='k',
            new_name='pword',
        ),
    ]
