"""empty message

Revision ID: c464ba4b0eab
Revises: 
Create Date: 2024-07-10 22:15:28.343387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c464ba4b0eab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('firstname', sa.String(length=80), nullable=False),
    sa.Column('lastname', sa.String(length=80), nullable=False),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('question_sets_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('question_set_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users_table.id'], ),
    sa.ForeignKeyConstraint(['question_set_id'], ['question_sets_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=80), nullable=False),
    sa.Column('answer', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('question_set_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games_table.id'], ),
    sa.ForeignKeyConstraint(['question_set_id'], ['question_sets_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers_table')
    op.drop_table('questions_table')
    op.drop_table('games_table')
    op.drop_table('question_sets_table')
    op.drop_table('users_table')
    # ### end Alembic commands ###
